name: 🔨 Build Test
on:
  push:
  pull_request:
  workflow_dispatch:


jobs:  
  build:
    name: Test Builds
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: stable

      - name: Check out code
        uses: actions/checkout@v7

      - name: Test
        run: go test ./...

      # TODO: create examples folder
      # - name: Build
      #   run: go build .